'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8689
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("pixie.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This text file was opened by the pixie://.
        '''</summary>
        Friend ReadOnly Property example() As String
            Get
                Return ResourceManager.GetString("example", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        '''&lt;HTML&gt;
        '''&lt;HEAD&gt;
        '''&lt;TITLE&gt; Pixie Help &lt;/TITLE&gt;
        '''&lt;META NAME=&quot;Author&quot; CONTENT=&quot;Si&quot;&gt;
        '''&lt;META NAME=&quot;Keywords&quot; CONTENT=&quot;Pixie&quot;&gt;
        '''&lt;META NAME=&quot;Description&quot; CONTENT=&quot;&quot;&gt;
        '''&lt;/HEAD&gt;
        '''
        '''&lt;BODY BGCOLOR=&quot;#FFFFFF&quot;&gt;
        '''&lt;a href=&quot;pixie://notepad?file=$PATH$\sfdc.xml&quot;&gt;Notepad&lt;/a&gt; 
        '''&lt;br&gt;
        '''&lt;a href=&quot;pixie://CONFIG&quot;&gt;Config&lt;/a&gt;
        '''&lt;br&gt;
        '''&lt;a href=&quot;pixie://log&quot;&gt;log&lt;/a&gt;
        '''&lt;/BODY&gt;
        '''&lt;/HTML&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property help() As String
            Get
                Return ResourceManager.GetString("help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;pixie&gt;
        '''  &lt;program
        '''    name=&quot;notepad&quot;
        '''    filename=&quot;notepad.exe&quot;
        '''    arguments=&quot;%file&quot;
        '''  /&gt; 
        ''' &lt;program
        '''    name=&quot;roofright&quot;
        '''    filename=&quot;roofright.exe&quot;
        '''    workingdirectory=&quot;c:\program files\roofright&quot;
        '''    arguments=&quot;-q %q&quot;
        '''  /&gt;
        '''&lt;/pixie&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property programs() As String
            Get
                Return ResourceManager.GetString("programs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;xs:element name=&quot;pixie&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;program&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:attribute name=&quot;name&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        '''            &lt;xs:attribute name=&quot;filename&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        '''            &lt;xs:attribute name=&quot;argume [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property valid() As String
            Get
                Return ResourceManager.GetString("valid", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
